In [1]:
import pandas as pd
df = pd.read_csv('../../data/coronavirus-covid-19-pandemic-usa-counties.csv', sep=';')
df['Date'] = pd.to_datetime(df['Date'])

df.head()

/home/pongpop/.local/lib/python3.8/site-packages/pandas/core/computation/expressions.py:20: UserWarning: Pandas requires version '2.7.3' or newer of 'numexpr' (version '2.7.1' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED

,Admin 2 FIPS Code,Province/State,Admin 2 Level (City/County/Borough/Region),Date,Total Death,Total Confirmed,location
0,12119.0,Florida,Sumter,2020-01-31,0,0,"28.70181754,-82.0794267"
1,13153.0,Georgia,Houston,2020-01-31,0,0,"32.45802497,-83.66879087"
2,13227.0,Georgia,Pickens,2020-01-31,0,0,"34.46589159,-84.46406611"
3,13303.0,Georgia,Washington,2020-01-31,0,0,"32.96711864,-82.79357039"
4,16003.0,Idaho,Adams,2020-01-31,0,0,"44.89333571,-116.4545247"

In [10]:
df[df.isna().any(axis=1)].head()

,Admin 2 FIPS Code,Province/State,Admin 2 Level (City/County/Borough/Region),Date,Total Death,Total Confirmed,location
30,NaN,Michigan,Michigan Department of Corrections (MDOC),2020-01-31,0,0,"0.0,0.0"
89,NaN,Utah,Southwest Utah,2020-01-31,0,0,"37.85447192,-111.4418764"
174,69.0,Northern Mariana Islands,NaN,2020-02-01,0,0,"15.0979,145.6739"
202,NaN,Utah,Southwest Utah,2020-02-01,0,0,"37.85447192,-111.4418764"
256,NaN,Missouri,Kansas City,2020-02-21,0,0,"39.0997,-94.5786"